#8083表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80
#服务别名----注册zookeeper到注册中心名称
spring:
  application:
    name: 002-springcloud-consumer-payment80
  cloud:
    zookeeper:
      connect-string: 192.168.84.129:2181