server:
  port: 80

spring:
  application:
    name: 005-springcloud-hystrix-consumer-80

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka

feign:
  hystrix:
    enabled: true #在Feign中开启Hystrix